### ISSUE TITLE
Login Page: Cannot read property 'randomBytes' of undefined

### ISSUE THREAD

**Issue by tverskih** [konsumer/aws-cognito-example#3]
Steps to reproduce:

1) Register new user
2) Logout
3) Press login
4) type in username and password
5) press login

You can see notification with message "Cannot read property 'randomBytes' of undefined"

Tested on Chrome 55, Mac OS 10.12.1

**Comment by nickksun** [comment]
Please see this pull request:

https://github.com/konsumer/aws-cognito-example/pull/4

**Comment by konsumer** [comment]
Closing, but feel free to add more, if the PR doesn't work for you.

**Comment by tverskih** [comment]
It works, thanks.
